service: MyParticleAlexaSkill-SRV

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
environment:
  PARTICLE_ACCESS_TOKEN: 7d2c1421777cb9487640bb72a2be6a42812cc20a

custom:
  defaultStage: dev
  profiles:
    dev: MyParticleAlexaSkill-SRV-profile-dev
    prod: MyParticleAlexaSkill-SRV-profile-prod

package:
  include:
    - particleUtils.js
    - skillUtils.js
    - node_modules/**

functions:
  handler:
    handler: index.handler
    role: arn:aws:iam::831933616546:role/lambda-dynamodb-execution-role
    events:
      - alexaSkill
